# Generated by Django 4.2.2 on 2023-11-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='booking_fee',
            field=models.IntegerField(null=True),
        ),
    ]
